version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend_api
    environment:
      DB_USER: peliculas
      DB_PASSWORD: 8VB3hiOxJDVlP8rIMcloMWWq1CBbE8nz
      DB_NAME: peliculas_h8in
      DB_HOST: dpg-cslbs1jv2p9s7383l90g-a
      DB_PORT: 5432
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend_api:8000