version: '3.8'
services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password  # Replace with your secure password
      POSTGRES_DB: movie_scripts        # Name of your database
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql

  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend_api
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: your_password
      DB_NAME: movie_scripts
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://backend_api:8000  

volumes:
  pgvector_data:
